backend:
  name: github
  repo: karkori/portfolio-nextjs 
  branch: main
  base_url: http://localhost:3000
  auth_endpoint: api/auth

# Para desarrollo local sin necesidad de Netlify
# local_backend: true
# local_backend:
#   url: http://localhost:8081/api/v1

# Rutas de medios
media_folder: public/images/blog
public_folder: /images/blog

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
      - {label: "Imagen de Portada", name: "thumbnail", widget: "image"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Categoría", name: "category", widget: "select", options: ["Desarrollo Web", "JavaScript", "React", "Next.js", "Diseño", "Otros"]}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}